ci: fix ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,72 +1,84 @@
 name: CI / Build & Test
-
-on:
+'on':
   push:
-    branches: [master]
+    branches:
+      - master
   pull_request:
-    branches: [master]
+    branches:
+      - master
   workflow_dispatch: {}
-
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref_name != 'master' && github.ref || github.run_id }}
+  group: >-
+    ${{ github.workflow }}-${{ github.ref_name != 'master' && github.ref ||
+    github.run_id }}
   cancel-in-progress: true
-
 env:
   CARGO_TERM_COLOR: always
-
 jobs:
   find-crates:
     name: Discover Crates
     runs-on: ubuntu-latest
     outputs:
-      crates: ${{ steps.list-crates.outputs.crates }}
-      filters: ${{ steps.list-crates.outputs.filters }}
+      crates: '${{ steps.list-crates.outputs.crates }}'
+      filters: '${{ steps.list-crates.outputs.filters }}'
     steps:
       - uses: actions/checkout@v4
       - id: list-crates
-        run: |
-          crates=$(find crates -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n")[:-1]')
+        run: >
+          crates=$(find crates -maxdepth 1 -mindepth 1 -type d -exec basename {}
+          \; | jq -R -s -c 'split("\n")[:-1]')
+
           echo "crates=$crates" >> $GITHUB_OUTPUT
-          filters=$(find crates -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read -r crate; do
+
+          filters=$(find crates -maxdepth 1 -mindepth 1 -type d -exec basename
+          {} \; | while read -r crate; do
             echo "${crate}:"
             echo "  - 'crates/${crate}/**'"
             echo "  - 'Cargo.toml'"
             echo "  - 'Cargo.lock'"
           done)
+
           filters="${filters}
+
           integration:
             - 'crates/**'
             - 'tests/**'
             - 'Cargo.toml'
             - 'Cargo.lock'"
           echo "filters<<EOF" >> $GITHUB_OUTPUT
-          echo "$filters" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
 
+          echo "$filters" >> $GITHUB_OUTPUT
+
+          echo "EOF" >> $GITHUB_OUTPUT
   changes:
     name: Detect Changes
     runs-on: ubuntu-latest
     needs: find-crates
     outputs:
-      crates: ${{ steps.filter.outputs.changes }}
-      integration: ${{ steps.filter.outputs.integration }}
+      crates: '${{ steps.build-outputs.outputs.crates }}'
+      testing: '${{ steps.filter.outputs.integration }}'
     steps:
       - uses: actions/checkout@v4
       - uses: dorny/paths-filter@v3
         id: filter
         with:
-          filters: ${{ needs.find-crates.outputs.filters }}
+          list-files: none
+          filters: '${{ needs.find-crates.outputs.filters }}'
+      - id: build-outputs
+        run: >
+          crates=$(echo '${{ steps.filter.outputs.changes }}' | jq -c '[.[] |
+          select(. != "integration")]')
 
+          echo "crates=$crates" >> $GITHUB_OUTPUT
   required:
     name: Required Checks
     runs-on: ubuntu-latest
-    if: always() # Always run to determine status of upstream jobs
+    if: always()
     needs:
       - build
       - integration-test
       - lint
       - test
-
     steps:
       - id: status
         name: Determine status
@@ -83,51 +95,47 @@ jobs:
           echo "results=$results" >> $GITHUB_OUTPUT
       - if: steps.status.outputs.result != 'success'
         name: Fail if any upstream failed
-        run: |
-          echo "One or more upstream jobs failed: ${{ steps.status.outputs.results }}"
-          exit 1
+        run: >
+          echo "One or more upstream jobs failed: ${{
+          steps.status.outputs.results }}"
 
+          exit 1
   build:
     name: Build - Workspace
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
       - name: Build
         run: cargo build --workspace --all-targets
-
   lint:
-    name: Lint, Format and Docs - Workspace
+    name: 'Lint, Format and Docs - Workspace'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
       - name: Run Clippy
         run: cargo clippy --workspace --all-targets -- -D warnings
-
       - name: Check Formatting
         run: cargo fmt --all -- --check
-
       - name: Check Docs
-        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --document-private-items
-
+        run: >-
+          RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps
+          --document-private-items
   test:
     name: Test - Crate
     runs-on: ubuntu-latest
     needs:
       - changes
       - find-crates
-    if: needs.changes.outputs.crates != '[]'
+    if: 'needs.changes.outputs.crates != ''[]'''
     strategy:
       matrix:
-        crate: ${{ fromJSON(needs.changes.outputs.crates) }}
+        crate: '${{ fromJSON(needs.changes.outputs.crates) }}'
     steps:
       - uses: actions/checkout@v4
-      - name: Run ${{ matrix.crate }} tests
-        run: cargo test -p ${{ matrix.crate }}
-
+      - name: 'Run ${{ matrix.crate }} tests'
+        run: 'cargo test -p ${{ matrix.crate }}'
   integration-test:
     name: Integration Test - Crate
     runs-on: ubuntu-latest
@@ -136,13 +144,10 @@ jobs:
       - build
       - test
     if: |
-      needs.changes.outputs.integration == 'true' &&
+      needs.changes.outputs.testing == 'true' &&
       needs.test.result != 'failure'
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
-        # FIXME: This timeout should be replaced with either something in the test itself
-        #  or something within the solver.
       - name: Run integration tests
         run: timeout 240s cargo netlib -- --nocapture
